version: '3.8'

services:
  # FastAPI应用服务
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gugugu-api
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - HOST=0.0.0.0
      - PORT=8000
      - PROJECT_NAME=Gugugu API
    volumes:
      - ./.env:/app/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
